<?php $qs = array_filter(['action' => input('action'), 'username' => input('username'), 'from' => input('from'), 'to' => input('to'), 'q' => input('q')]); ?>
<div class="d-flex justify-content-between mb-3"><h4>Audit Logs <span class="badge text-bg-light"><?= (int)$total ?></span></h4><a class="btn btn-outline-secondary" href="<?= url('audit/index', $qs + ['export' => 'csv']) ?>"><i class="bi bi-download"></i> CSV</a></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="audit/index">
 <div class="col-md-2"><select class="form-select" name="action"><option value="">All actions</option><?php foreach ($actions as $a): ?><option <?= input('action') === $a ? 'selected' : '' ?>><?= e($a) ?></option><?php endforeach; ?></select></div>
 <div class="col-md-2"><select class="form-select" name="username"><option value="">All users</option><?php foreach ($users as $u): ?><option <?= input('username') === $u ? 'selected' : '' ?>><?= e($u) ?></option><?php endforeach; ?></select></div>
 <div class="col-md-2"><input type="date" class="form-control" name="from" value="<?= e(input('from')) ?>"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="<?= e(input('to')) ?>"></div>
 <div class="col-md-3"><input class="form-control" name="q" value="<?= e(input('q')) ?>" placeholder="Search entity / details"></div><div class="col-auto"><button class="btn btn-outline-secondary"><i class="bi bi-search"></i></button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0 small"><thead class="table-light"><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Details</th><th>IP</th></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><td class="text-nowrap"><?= e($r['created_at']) ?></td><td><?= e($r['username']) ?></td><td><span class="badge text-bg-secondary"><?= e($r['action']) ?></span></td><td><?= e($r['entity'] . ($r['entity_id'] !== null ? ' #' . $r['entity_id'] : '')) ?></td><td style="max-width:420px;word-break:break-word"><?= e(mb_strimwidth((string)$r['details'], 0, 300, '…')) ?></td><td><?= e($r['ip']) ?></td></tr><?php endforeach; ?>
<?php if (!$rows): ?><tr><td colspan="6" class="text-center text-muted py-3">No entries.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if ($pages > 1): ?><nav class="mt-3"><ul class="pagination pagination-sm"><?php for ($i = max(1, $page - 4); $i <= min($pages, $page + 4); $i++): ?><li class="page-item <?= $i === $page ? 'active' : '' ?>"><a class="page-link" href="<?= url('audit/index', $qs + ['page' => $i]) ?>"><?= $i ?></a></li><?php endfor; ?></ul></nav><?php endif; ?>
