<?php $id = $row['id'] ?? 0; $o = $_SESSION['_old'] ?? []; $val = fn($k) => $o[$k] ?? ($row[$k] ?? ''); $err = fn($k) => $errors[$k] ?? null; $oldRoles = isset($o['roles']) ? array_map('intval', $o['roles']) : $mine; ?>
<div class="d-flex justify-content-between mb-3"><h4><?= e($title) ?></h4><a class="btn btn-outline-secondary" href="<?= url('users/index') ?>"><i class="bi bi-arrow-left"></i> Back</a></div>
<form method="post" action="<?= url('users/save') ?>" class="card card-body needs-validation" novalidate autocomplete="off"><?= csrf_field() ?><?php if ($id): ?><input type="hidden" name="id" value="<?= (int)$id ?>"><?php endif; ?>
<div class="row g-3">
 <?php foreach ([['username', 'Username', 'text', 1], ['full_name', 'Full name', 'text', 1], ['email', 'Email', 'email', 0], ['phone', 'Phone', 'text', 0]] as [$k, $l, $t, $req]): ?>
  <div class="col-md-6"><label class="form-label <?= $req ? 'required-star' : '' ?>"><?= $l ?></label><input type="<?= $t ?>" name="<?= $k ?>" class="form-control <?= $err($k) ? 'is-invalid' : '' ?>" value="<?= e($val($k)) ?>" <?= $req ? 'required' : '' ?> maxlength="120"><div class="invalid-feedback"><?= e($err($k) ?? 'Required.') ?></div></div>
 <?php endforeach; ?>
 <?php if (!$id): ?><div class="col-md-6"><label class="form-label required-star">Temporary password</label><input type="password" name="password" class="form-control <?= $err('password') ? 'is-invalid' : '' ?>" required autocomplete="new-password"><div class="invalid-feedback"><?= e($err('password') ?? 'Required.') ?></div><div class="form-text">8+ chars with upper-case, lower-case and a digit. User must change it at first login.</div></div><?php endif; ?>
 <div class="col-md-6"><label class="form-label">Linked employee</label><select name="employee_id" class="form-select <?= $err('employee_id') ? 'is-invalid' : '' ?>"><option value="">-- None --</option><?php foreach ($emps as $e2): ?><option value="<?= (int)$e2['id'] ?>" <?= (string)$val('employee_id') === (string)$e2['id'] ? 'selected' : '' ?>><?= e($e2['emp_no'] . ' - ' . $e2['full_name']) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($err('employee_id')) ?></div></div>
 <div class="col-md-6"><label class="form-label">Branch</label><select name="branch_id" class="form-select"><option value="">-- None --</option><?php foreach ($branches as $b): ?><option value="<?= (int)$b['id'] ?>" <?= (string)$val('branch_id') === (string)$b['id'] ? 'selected' : '' ?>><?= e($b['name']) ?></option><?php endforeach; ?></select></div>
 <?php if (Auth::can('admin.users.assign_role')): ?><div class="col-12"><label class="form-label">Roles</label><div class="d-flex flex-wrap gap-3">
  <?php foreach ($roles as $r): ?><div class="form-check"><input class="form-check-input" type="checkbox" name="roles[]" value="<?= (int)$r['id'] ?>" id="r<?= (int)$r['id'] ?>" <?= in_array((int)$r['id'], $oldRoles, true) ? 'checked' : '' ?>><label class="form-check-label" for="r<?= (int)$r['id'] ?>"><?= e($r['name']) ?></label></div><?php endforeach; ?></div></div><?php endif; ?>
</div><div class="mt-4"><button class="btn btn-primary once"><i class="bi bi-check-lg"></i> Save</button></div></form>
