<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Users</h4><?php if (Auth::can('admin.users.create')): ?><a class="btn btn-primary" href="<?= url('users/form') ?>"><i class="bi bi-plus-lg"></i> New user</a><?php endif; ?></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="users/index"><div class="col-md-4"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="Search username, name, email"></div><div class="col-auto"><button class="btn btn-outline-secondary"><i class="bi bi-search"></i></button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0 align-middle"><thead class="table-light"><tr><th>Username</th><th>Name</th><th>Roles</th><th>Branch</th><th>Last login</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php foreach ($users as $u): ?><tr>
 <td><?= e($u['username']) ?></td><td><?= e($u['full_name']) ?></td><td><?= e($u['roles'] ?: '-') ?></td><td><?= e($u['branch_name']) ?></td><td class="small"><?= e(fmt_date($u['last_login_at'], 'd M Y H:i')) ?></td>
 <td><?= badge($u['is_active'] ? 'active' : 'inactive') ?> <?php if ($u['is_locked'] || ($u['locked_until'] && strtotime($u['locked_until']) > time())): ?><span class="badge text-bg-danger">Locked</span><?php endif; ?></td>
 <td class="text-end text-nowrap">
  <?php if (Auth::can('admin.users.edit')): ?><a class="btn btn-sm btn-outline-primary" title="Edit" href="<?= url('users/form', ['id' => $u['id']]) ?>"><i class="bi bi-pencil"></i></a><?php endif; ?>
  <?php if (Auth::can('admin.users.reset_password')): ?><a class="btn btn-sm btn-outline-secondary" title="Reset password" href="<?= url('users/reset', ['id' => $u['id']]) ?>"><i class="bi bi-key"></i></a><?php endif; ?>
  <?php if (Auth::can('admin.users.activate')): ?><form method="post" action="<?= url('users/toggle') ?>" class="d-inline" data-confirm="Change active status?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><button class="btn btn-sm btn-outline-warning" title="Activate / deactivate"><i class="bi bi-toggle-on"></i></button></form><?php endif; ?>
  <?php if (Auth::can('admin.users.lock')): ?><form method="post" action="<?= url('users/lock') ?>" class="d-inline"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><button class="btn btn-sm btn-outline-danger" title="Lock / unlock"><i class="bi bi-<?= $u['is_locked'] ? 'unlock' : 'lock' ?>"></i></button></form><?php endif; ?>
 </td></tr><?php endforeach; ?></tbody></table></div></div>
