<?php
// Declarative CRUD entities used by CrudController.
// field keys: name,label,type(text|email|number|decimal|date|textarea|select|checkbox|image),rules,options,source[table,id,label,where],nullable,default,readonly_edit,auto[seq,prefix,pad],unique,help
$active = ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => 1];
$status = fn($o) => ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => $o, 'rules' => 'required'];
$src = fn($t, $l = 'name', $w = '1=1') => ['source' => [$t, 'id', $l, $w]];

$productCommon = fn() => [
    ['name' => 'sku', 'label' => 'SKU', 'type' => 'text', 'rules' => 'max:40|code', 'unique' => true, 'help' => 'Leave blank to auto-generate.'],
    ['name' => 'barcode', 'label' => 'Barcode', 'type' => 'text', 'rules' => 'max:40|code', 'unique' => true, 'nullable' => true, 'help' => 'Leave blank to auto-generate an in-store EAN-13.'],
    ['name' => 'category_id', 'label' => 'Category', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:categories,id'] + $src('categories', 'name', 'is_active=1'),
    ['name' => 'unit_id', 'label' => 'Unit', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:units,id'] + $src('units'),
    ['name' => 'cost_price', 'label' => 'Cost price', 'type' => 'decimal', 'rules' => 'required|decimal', 'default' => 0, 'price' => true],
    ['name' => 'selling_price', 'label' => 'Selling price', 'type' => 'decimal', 'rules' => 'required|decimal', 'default' => 0, 'price' => true],
    ['name' => 'wholesale_price', 'label' => 'Wholesale price', 'type' => 'decimal', 'rules' => 'decimal', 'nullable' => true, 'price' => true],
    ['name' => 'member_price', 'label' => 'Member price', 'type' => 'decimal', 'rules' => 'decimal', 'nullable' => true, 'price' => true],
    ['name' => 'tax_rate', 'label' => 'Tax rate % (blank = system default)', 'type' => 'decimal', 'rules' => 'decimal|maxval:100', 'nullable' => true],
    ['name' => 'reorder_level', 'label' => 'Reorder level', 'type' => 'number', 'rules' => 'required|int|minval:0', 'default' => 0],
    ['name' => 'min_stock', 'label' => 'Minimum stock', 'type' => 'number', 'rules' => 'required|int|minval:0', 'default' => 0],
    ['name' => 'max_stock', 'label' => 'Maximum stock (overstock alert)', 'type' => 'number', 'rules' => 'int|minval:0', 'nullable' => true],
    ['name' => 'image', 'label' => 'Product image', 'type' => 'image'],
    ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rules' => 'max:2000', 'nullable' => true],
    ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => 1],
];
$productList = ['image' => ['', 'image'], 'sku' => 'SKU', 'name' => 'Name', 'category_name' => 'Category', 'cost_price' => ['Cost', 'money'], 'selling_price' => ['Price', 'money'], 'is_active' => ['Status', 'active']];
$productFrom = 'products t LEFT JOIN categories c ON c.id=t.category_id LEFT JOIN brands b ON b.id=t.brand_id LEFT JOIN authors a ON a.id=t.author_id LEFT JOIN publishers pu ON pu.id=t.publisher_id';
$productCols = 't.*, c.name AS category_name, b.name AS brand_name, a.name AS author_name, pu.name AS publisher_name';
$productFilters = [['name' => 'category_id', 'label' => 'Category', 'source' => ['categories', 'id', 'name', 'is_active=1']]];
$productActions = [['Barcode', 'products/label&id={id}', 'inventory.products.view', 'bi-upc'], ['Price history', 'products/history&id={id}', 'inventory.products.view', 'bi-graph-up']];

$bookFields = array_merge([
    ['name' => 'isbn', 'label' => 'ISBN', 'type' => 'text', 'rules' => 'required|isbn|max:20', 'unique' => true, 'help' => 'ISBN-10 or ISBN-13 (checksum validated).'],
    ['name' => 'name', 'label' => 'Title', 'type' => 'text', 'rules' => 'required|max:200'],
    ['name' => 'author_id', 'label' => 'Author', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:authors,id'] + $src('authors', 'name', 'is_active=1'),
    ['name' => 'publisher_id', 'label' => 'Publisher', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:publishers,id'] + $src('publishers', 'name', 'is_active=1'),
    ['name' => 'edition', 'label' => 'Edition', 'type' => 'text', 'rules' => 'max:40', 'nullable' => true],
    ['name' => 'language', 'label' => 'Language', 'type' => 'text', 'rules' => 'max:40', 'nullable' => true],
    ['name' => 'genre', 'label' => 'Genre', 'type' => 'text', 'rules' => 'max:80', 'nullable' => true],
    ['name' => 'pub_year', 'label' => 'Publication year', 'type' => 'number', 'rules' => 'int|minval:1400|maxval:2100', 'nullable' => true],
], $productCommon());

$stationeryFields = array_merge([
    ['name' => 'name', 'label' => 'Product name', 'type' => 'text', 'rules' => 'required|max:200'],
    ['name' => 'brand_id', 'label' => 'Brand', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:brands,id'] + $src('brands', 'name', 'is_active=1'),
    ['name' => 'size', 'label' => 'Size', 'type' => 'text', 'rules' => 'max:40', 'nullable' => true],
    ['name' => 'color', 'label' => 'Colour', 'type' => 'text', 'rules' => 'max:40', 'nullable' => true],
    ['name' => 'pack_qty', 'label' => 'Pack quantity', 'type' => 'number', 'rules' => 'int|minval:1', 'nullable' => true],
    ['name' => 'parent_id', 'label' => 'Variant of (parent product)', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:products,id'] + $src('products', 'name', "product_type='stationery' AND parent_id IS NULL"),
], $productCommon());

$allFields = array_merge([
    ['name' => 'product_type', 'label' => 'Type', 'type' => 'select', 'options' => ['other' => 'Other', 'book' => 'Book', 'stationery' => 'Stationery'], 'rules' => 'required|in:book,stationery,other'],
    ['name' => 'name', 'label' => 'Product name', 'type' => 'text', 'rules' => 'required|max:200'],
    ['name' => 'brand_id', 'label' => 'Brand', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:brands,id'] + $src('brands', 'name', 'is_active=1'),
], $productCommon());

return [
    'employees' => ['title' => 'Employees', 'table' => 'employees', 'perm' => 'admin.employees', 'order' => 't.full_name',
        'from' => 'employees t LEFT JOIN branches b ON b.id=t.branch_id', 'cols' => 't.*, b.name AS branch_name',
        'list' => ['emp_no' => 'Emp No', 'full_name' => 'Name', 'designation' => 'Designation', 'phone' => 'Phone', 'branch_name' => 'Branch', 'status' => ['Status', 'badge']],
        'search' => ['t.emp_no', 't.full_name', 't.nic', 't.phone'], 'soft' => ['status', 'active', 'inactive'],
        'fields' => [
            ['name' => 'emp_no', 'label' => 'Employee No', 'type' => 'text', 'rules' => 'max:20|code', 'unique' => true, 'auto' => ['employee', 'EMP-', 4], 'readonly_edit' => true, 'help' => 'Auto-generated if blank.'],
            ['name' => 'full_name', 'label' => 'Full name', 'type' => 'text', 'rules' => 'required|max:150'],
            ['name' => 'nic', 'label' => 'NIC', 'type' => 'text', 'rules' => 'max:20|code', 'nullable' => true],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'phone', 'nullable' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'rules' => 'email|max:120', 'nullable' => true],
            ['name' => 'address', 'label' => 'Address', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            ['name' => 'designation', 'label' => 'Designation', 'type' => 'text', 'rules' => 'max:80', 'nullable' => true],
            ['name' => 'branch_id', 'label' => 'Branch', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:branches,id'] + $src('branches', 'name', 'is_active=1'),
            ['name' => 'hire_date', 'label' => 'Hire date', 'type' => 'date', 'rules' => 'date', 'nullable' => true],
            $status(['active' => 'Active', 'inactive' => 'Inactive']),
        ]],
    'branches' => ['title' => 'Branches', 'table' => 'branches', 'perm' => 'admin.branches', 'order' => 't.name',
        'list' => ['code' => 'Code', 'name' => 'Name', 'phone' => 'Phone', 'tax_rate' => 'Tax %', 'is_active' => ['Status', 'active']], 'search' => ['t.code', 't.name'],
        'fields' => [
            ['name' => 'code', 'label' => 'Code', 'type' => 'text', 'rules' => 'required|max:20|code', 'unique' => true],
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|max:120'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'phone', 'nullable' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'rules' => 'email|max:120', 'nullable' => true],
            ['name' => 'tax_rate', 'label' => 'Branch tax rate % (blank = system default)', 'type' => 'decimal', 'rules' => 'decimal|maxval:100', 'nullable' => true],
            ['name' => 'receipt_footer', 'label' => 'Receipt footer', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            $active]],
    'warehouses' => ['title' => 'Warehouses / Store locations', 'table' => 'warehouses', 'perm' => 'admin.branches', 'order' => 'b.name, t.name',
        'from' => 'warehouses t JOIN branches b ON b.id=t.branch_id', 'cols' => 't.*, b.name AS branch_name',
        'list' => ['name' => 'Name', 'branch_name' => 'Branch', 'location' => 'Location', 'is_default' => ['Default', 'bool'], 'is_active' => ['Status', 'active']], 'search' => ['t.name', 'b.name'],
        'row_actions' => [['Stock', 'stock/index&warehouse={id}', 'inventory.stock.view', 'bi-boxes']],
        'fields' => [
            ['name' => 'branch_id', 'label' => 'Branch', 'type' => 'select', 'rules' => 'required|exists:branches,id'] + $src('branches', 'name', 'is_active=1'),
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|max:120'],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text', 'rules' => 'max:160', 'nullable' => true],
            ['name' => 'is_default', 'label' => 'Default warehouse of the branch (used by POS)', 'type' => 'checkbox', 'default' => 0], $active]],
    'counters' => ['title' => 'POS Counters / Registers', 'table' => 'counters', 'perm' => 'admin.branches', 'order' => 'b.name, t.name',
        'from' => 'counters t JOIN branches b ON b.id=t.branch_id', 'cols' => 't.*, b.name AS branch_name',
        'list' => ['name' => 'Counter', 'branch_name' => 'Branch', 'is_active' => ['Status', 'active']], 'search' => ['t.name', 'b.name'],
        'fields' => [['name' => 'branch_id', 'label' => 'Branch', 'type' => 'select', 'rules' => 'required|exists:branches,id'] + $src('branches', 'name', 'is_active=1'),
            ['name' => 'name', 'label' => 'Counter name', 'type' => 'text', 'rules' => 'required|max:80'], $active]],
    'suppliers' => ['title' => 'Suppliers', 'table' => 'suppliers', 'perm' => 'admin.suppliers', 'order' => 't.name',
        'list' => ['code' => 'Code', 'name' => 'Name', 'contact_person' => 'Contact', 'phone' => 'Phone', 'payment_terms' => 'Terms', 'is_active' => ['Status', 'active']],
        'search' => ['t.code', 't.name', 't.phone', 't.contact_person'], 'row_actions' => [['Profile', 'supplier/view&id={id}', 'admin.suppliers.view', 'bi-eye']],
        'fields' => [
            ['name' => 'code', 'label' => 'Code', 'type' => 'text', 'rules' => 'max:20|code', 'unique' => true, 'auto' => ['supplier', 'SUP-', 4], 'readonly_edit' => true, 'help' => 'Auto-generated if blank.'],
            ['name' => 'name', 'label' => 'Supplier name', 'type' => 'text', 'rules' => 'required|max:150'],
            ['name' => 'contact_person', 'label' => 'Contact person', 'type' => 'text', 'rules' => 'max:120', 'nullable' => true],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'phone', 'nullable' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'rules' => 'email|max:120', 'nullable' => true],
            ['name' => 'address', 'label' => 'Address', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            ['name' => 'payment_terms', 'label' => 'Payment terms', 'type' => 'text', 'rules' => 'max:80', 'nullable' => true],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea', 'rules' => 'max:1000', 'nullable' => true], $active]],
    'customer_groups' => ['title' => 'Customer Groups', 'table' => 'customer_groups', 'perm' => 'admin.customers', 'order' => 't.name',
        'list' => ['name' => 'Group', 'price_type' => 'Price type', 'discount_percent' => 'Discount %', 'is_active' => ['Status', 'active']], 'search' => ['t.name'],
        'fields' => [['name' => 'name', 'label' => 'Group name', 'type' => 'text', 'rules' => 'required|max:80', 'unique' => true],
            ['name' => 'price_type', 'label' => 'Price type', 'type' => 'select', 'options' => ['retail' => 'Retail', 'wholesale' => 'Wholesale', 'member' => 'Member'], 'rules' => 'required|in:retail,wholesale,member'],
            ['name' => 'discount_percent', 'label' => 'Standing discount %', 'type' => 'decimal', 'rules' => 'required|decimal|maxval:100', 'default' => 0], $active]],
    'customers' => ['title' => 'Customers', 'table' => 'customers', 'perm' => 'admin.customers', 'order' => 't.name',
        'from' => 'customers t LEFT JOIN customer_groups g ON g.id=t.group_id', 'cols' => 't.*, g.name AS group_name',
        'list' => ['code' => 'Code', 'name' => 'Name', 'phone' => 'Phone', 'group_name' => 'Group', 'credit_limit' => ['Credit limit', 'money'], 'loyalty_points' => 'Points', 'is_active' => ['Status', 'active']],
        'search' => ['t.code', 't.name', 't.phone', 't.email'], 'row_actions' => [['Profile', 'customer/view&id={id}', 'admin.customers.view', 'bi-eye']],
        'fields' => [
            ['name' => 'code', 'label' => 'Code', 'type' => 'text', 'rules' => 'max:20|code', 'unique' => true, 'auto' => ['customer', 'CUS-', 5], 'readonly_edit' => true, 'help' => 'Auto-generated if blank.'],
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|max:150'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'phone', 'nullable' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'rules' => 'email|max:120', 'nullable' => true],
            ['name' => 'address', 'label' => 'Address', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            ['name' => 'group_id', 'label' => 'Customer group', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:customer_groups,id'] + $src('customer_groups', 'name', 'is_active=1'),
            ['name' => 'credit_limit', 'label' => 'Credit limit', 'type' => 'decimal', 'rules' => 'required|decimal', 'default' => 0, 'help' => '0 = no credit sales.'], $active]],
    'price_lists' => ['title' => 'Price Lists', 'table' => 'price_lists', 'perm' => 'admin.pricing', 'order' => 't.name',
        'from' => 'price_lists t LEFT JOIN customer_groups g ON g.id=t.customer_group_id', 'cols' => 't.*, g.name AS group_name',
        'list' => ['name' => 'Name', 'group_name' => 'Customer group', 'start_date' => ['From', 'date'], 'end_date' => ['To', 'date'], 'is_active' => ['Status', 'active']], 'search' => ['t.name'],
        'row_actions' => [['Items', 'pricing/items&id={id}', 'admin.pricing.view', 'bi-list-ul']],
        'fields' => [['name' => 'name', 'label' => 'Price list name', 'type' => 'text', 'rules' => 'required|max:100'],
            ['name' => 'customer_group_id', 'label' => 'Applies to customer group', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:customer_groups,id'] + $src('customer_groups', 'name', 'is_active=1'),
            ['name' => 'start_date', 'label' => 'Valid from (scheduled)', 'type' => 'date', 'rules' => 'date', 'nullable' => true],
            ['name' => 'end_date', 'label' => 'Valid to', 'type' => 'date', 'rules' => 'date', 'nullable' => true], $active]],
    'promotions' => ['title' => 'Promotions & Discount Rules', 'table' => 'promotions', 'perm' => 'admin.pricing', 'order' => 't.id DESC',
        'list' => ['name' => 'Name', 'type' => 'Type', 'value' => 'Value', 'scope' => 'Scope', 'min_qty' => 'Min qty', 'coupon_code' => 'Coupon', 'start_date' => ['From', 'date'], 'end_date' => ['To', 'date'], 'is_active' => ['Status', 'active']], 'search' => ['t.name', 't.coupon_code'],
        'fields' => [['name' => 'name', 'label' => 'Promotion name', 'type' => 'text', 'rules' => 'required|max:120'],
            ['name' => 'type', 'label' => 'Discount type', 'type' => 'select', 'options' => ['percent' => 'Percentage %', 'fixed' => 'Fixed amount per unit'], 'rules' => 'required|in:percent,fixed'],
            ['name' => 'value', 'label' => 'Value', 'type' => 'decimal', 'rules' => 'required|pos'],
            ['name' => 'scope', 'label' => 'Applies to', 'type' => 'select', 'options' => ['all' => 'All products', 'category' => 'Category', 'product' => 'Single product'], 'rules' => 'required|in:all,category,product'],
            ['name' => 'category_id', 'label' => 'Category (if scope = category)', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:categories,id'] + $src('categories'),
            ['name' => 'product_id', 'label' => 'Product (if scope = product)', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:products,id'] + $src('products', 'name', 'is_archived=0'),
            ['name' => 'min_qty', 'label' => 'Minimum quantity (quantity discount)', 'type' => 'number', 'rules' => 'required|int|minval:1', 'default' => 1],
            ['name' => 'customer_group_id', 'label' => 'Only for customer group', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:customer_groups,id'] + $src('customer_groups'),
            ['name' => 'coupon_code', 'label' => 'Coupon code (blank = automatic)', 'type' => 'text', 'rules' => 'max:30|code', 'nullable' => true],
            ['name' => 'start_date', 'label' => 'Start date', 'type' => 'date', 'rules' => 'date', 'nullable' => true],
            ['name' => 'end_date', 'label' => 'End date', 'type' => 'date', 'rules' => 'date', 'nullable' => true], $active]],
    'expenses' => ['title' => 'Expenses', 'table' => 'expenses', 'perm' => 'admin.finance', 'order' => 't.id DESC',
        'from' => 'expenses t LEFT JOIN branches b ON b.id=t.branch_id', 'cols' => 't.*, b.name AS branch_name',
        'list' => ['expense_no' => 'No', 'expense_date' => ['Date', 'date'], 'category' => 'Category', 'description' => 'Description', 'amount' => ['Amount', 'money'], 'method' => 'Method', 'status' => ['Status', 'badge']],
        'search' => ['t.expense_no', 't.category', 't.description'], 'lock_if' => ['status' => ['approved', 'rejected']], 'on_create' => ['status' => 'pending', 'created_by' => '@user'],
        'row_actions' => [['Approve', 'finance/expense_decide&decision=approved&id={id}', 'admin.finance.approve', 'bi-check-lg', ['status' => 'pending'], true], ['Reject', 'finance/expense_decide&decision=rejected&id={id}', 'admin.finance.approve', 'bi-x-lg', ['status' => 'pending'], true]],
        'fields' => [['name' => 'expense_no', 'label' => 'Expense No', 'type' => 'text', 'rules' => 'max:30', 'unique' => true, 'auto' => ['expense', 'EXP-', 5], 'readonly_edit' => true],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text', 'rules' => 'required|max:80', 'list' => ['Rent', 'Electricity', 'Water', 'Salaries', 'Transport', 'Maintenance', 'Marketing', 'Miscellaneous']],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'rules' => 'max:255', 'nullable' => true],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'decimal', 'rules' => 'required|pos'],
            ['name' => 'expense_date', 'label' => 'Date', 'type' => 'date', 'rules' => 'required|date', 'default' => date('Y-m-d')],
            ['name' => 'method', 'label' => 'Paid from', 'type' => 'select', 'options' => payment_methods(), 'rules' => 'required|in:cash,card,bank_transfer,digital'],
            ['name' => 'branch_id', 'label' => 'Branch', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:branches,id'] + $src('branches', 'name', 'is_active=1')]],
    'categories' => ['title' => 'Categories', 'table' => 'categories', 'perm' => 'inventory.categories', 'order' => 'COALESCE(p.name, t.name), t.parent_id IS NOT NULL, t.name',
        'from' => 'categories t LEFT JOIN categories p ON p.id=t.parent_id', 'cols' => 't.*, p.name AS parent_name',
        'list' => ['name' => 'Category', 'parent_name' => 'Parent', 'is_active' => ['Status', 'active']], 'search' => ['t.name', 'p.name'],
        'fields' => [['name' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|max:100'],
            ['name' => 'parent_id', 'label' => 'Parent category', 'type' => 'select', 'nullable' => true, 'rules' => 'exists:categories,id'] + $src('categories'), $active]],
    'brands' => ['title' => 'Brands', 'table' => 'brands', 'perm' => 'inventory.categories', 'order' => 't.name', 'list' => ['name' => 'Brand', 'is_active' => ['Status', 'active']], 'search' => ['t.name'],
        'fields' => [['name' => 'name', 'label' => 'Brand name', 'type' => 'text', 'rules' => 'required|max:100', 'unique' => true], $active]],
    'authors' => ['title' => 'Authors', 'table' => 'authors', 'perm' => 'inventory.categories', 'order' => 't.name', 'list' => ['name' => 'Author', 'is_active' => ['Status', 'active']], 'search' => ['t.name'],
        'fields' => [['name' => 'name', 'label' => 'Author name', 'type' => 'text', 'rules' => 'required|max:150', 'unique' => true], $active]],
    'publishers' => ['title' => 'Publishers', 'table' => 'publishers', 'perm' => 'inventory.categories', 'order' => 't.name', 'list' => ['name' => 'Publisher', 'is_active' => ['Status', 'active']], 'search' => ['t.name'],
        'fields' => [['name' => 'name', 'label' => 'Publisher name', 'type' => 'text', 'rules' => 'required|max:150', 'unique' => true], $active]],
    'units' => ['title' => 'Units', 'table' => 'units', 'perm' => 'inventory.categories', 'order' => 't.name', 'list' => ['name' => 'Unit', 'short_name' => 'Short'], 'search' => ['t.name'],
        'fields' => [['name' => 'name', 'label' => 'Unit name', 'type' => 'text', 'rules' => 'required|max:40', 'unique' => true], ['name' => 'short_name', 'label' => 'Short name', 'type' => 'text', 'rules' => 'required|max:10']]],
    'products' => ['title' => 'All Products', 'table' => 'products', 'perm' => 'inventory.products', 'order' => 't.name', 'from' => $productFrom, 'cols' => $productCols, 'where' => 't.is_archived=0',
        'archive' => true, 'list' => $productList + [], 'search' => ['t.name', 't.sku', 't.barcode', 't.isbn'], 'filters' => $productFilters, 'row_actions' => $productActions, 'fields' => $allFields],
    'books' => ['title' => 'Books', 'table' => 'products', 'perm' => 'inventory.books', 'order' => 't.name', 'from' => $productFrom, 'cols' => $productCols, 'where' => "t.is_archived=0 AND t.product_type='book'",
        'archive' => true, 'force' => ['product_type' => 'book'], 'search' => ['t.name', 't.isbn', 't.sku', 't.barcode', 'a.name', 'pu.name'], 'filters' => $productFilters, 'row_actions' => $productActions,
        'list' => ['image' => ['', 'image'], 'isbn' => 'ISBN', 'name' => 'Title', 'author_name' => 'Author', 'publisher_name' => 'Publisher', 'selling_price' => ['Price', 'money'], 'is_active' => ['Status', 'active']], 'fields' => $bookFields],
    'stationery' => ['title' => 'Stationery', 'table' => 'products', 'perm' => 'inventory.stationery', 'order' => 't.name', 'from' => $productFrom, 'cols' => $productCols, 'where' => "t.is_archived=0 AND t.product_type='stationery'",
        'archive' => true, 'force' => ['product_type' => 'stationery'], 'search' => ['t.name', 't.sku', 't.barcode', 'b.name'], 'filters' => $productFilters, 'row_actions' => $productActions,
        'list' => ['image' => ['', 'image'], 'sku' => 'SKU', 'name' => 'Name', 'brand_name' => 'Brand', 'color' => 'Colour', 'pack_qty' => 'Pack', 'selling_price' => ['Price', 'money'], 'is_active' => ['Status', 'active']], 'fields' => $stationeryFields],
];
