<?php $qs = array_filter(['from' => $from, 'to' => $to, 'q' => input('q'), 'status' => input('status'), 'cashier' => input('cashier')]); ?>
<div class="d-flex justify-content-between mb-3"><h4>Transactions</h4><a class="btn btn-outline-secondary" href="<?= url('pos/history', $qs + ['export' => 'csv']) ?>"><i class="bi bi-download"></i> CSV</a></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="pos/history"><div class="col-md-2"><input type="date" class="form-control" name="from" value="<?= e($from) ?>"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="<?= e($to) ?>"></div><div class="col-md-3"><input class="form-control" name="q" value="<?= e(input('q')) ?>" placeholder="Invoice / customer / phone"></div>
<div class="col-md-2"><select class="form-select" name="status"><option value="">All</option><option value="completed" <?= input('status') === 'completed' ? 'selected' : '' ?>>Completed</option><option value="void" <?= input('status') === 'void' ? 'selected' : '' ?>>Void</option></select></div>
<?php if ($all): ?><div class="col-md-2"><select class="form-select" name="cashier"><option value="">All cashiers</option><?php foreach ($cashiers as $c): ?><option value="<?= (int)$c['id'] ?>" <?= input('cashier') == $c['id'] ? 'selected' : '' ?>><?= e($c['full_name']) ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="col-auto"><button class="btn btn-outline-secondary"><i class="bi bi-search"></i></button></div></form>
<div class="alert alert-light border"><?= (int)$sum['n'] ?> transaction(s) &middot; completed total <b><?= e(money($sum['t'])) ?></b></div>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>Invoice</th><th>Date</th><th>Cashier</th><th>Customer</th><th class="text-end">Total</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><td><a href="<?= url('pos/sale', ['id' => $r['id']]) ?>"><?= e($r['invoice_no']) ?></a></td><td><?= e(fmt_date($r['sale_date'], 'd M H:i')) ?></td><td><?= e($r['cashier']) ?></td><td><?= e($r['customer']) ?></td><td class="text-end"><?= number_format($r['total'], 2) ?></td><td><?= badge($r['status']) ?> <?= $r['returns_n'] ? '<span class="badge text-bg-warning">Returned</span>' : '' ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="<?= url('pos/sale', ['id' => $r['id']]) ?>"><i class="bi bi-eye"></i></a></td></tr><?php endforeach; ?>
<?php if (!$rows): ?><tr><td colspan="7" class="text-center text-muted py-3">No transactions.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if ($pages > 1): ?><nav class="mt-3"><ul class="pagination pagination-sm"><?php for ($i = max(1, $page - 4); $i <= min($pages, $page + 4); $i++): ?><li class="page-item <?= $i === $page ? 'active' : '' ?>"><a class="page-link" href="<?= url('pos/history', $qs + ['page' => $i]) ?>"><?= $i ?></a></li><?php endfor; ?></ul></nav><?php endif; ?>
