<?php $inv = $mode === 'invoice'; $biz = setting('business_name', cfg('app_name')); $public = $public ?? false; ?>
<!doctype html><html><head><meta charset="utf-8"><title><?= e($s['invoice_no']) ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>body{background:#f4f4f4}.sheet{background:#fff;margin:12px auto;padding:14px}.r80{width:80mm;font-family:monospace;font-size:12px}.a4{max-width:210mm;font-size:14px;padding:24px}.r80 table{width:100%}.r80 .l td{padding:1px 0;vertical-align:top}.dash{border-top:1px dashed #000;margin:6px 0}@media print{body{background:#fff}.bar{display:none}.sheet{margin:0}@page{margin:4mm}}</style></head><body>
<div class="bar text-center p-2 bg-white border-bottom"><button class="btn btn-sm btn-primary" onclick="window.print()">Print</button> <?php if (!$public): ?><a class="btn btn-sm btn-outline-secondary" href="<?= url($inv ? 'pos/receipt' : 'pos/invoice', ['id' => $s['id'], 'noprint' => 1]) ?>"><?= $inv ? 'Receipt' : 'A4 Invoice' ?></a> <a class="btn btn-sm btn-outline-secondary" href="<?= url('pos/sale', ['id' => $s['id']]) ?>">Back</a><?php endif; ?></div>
<?php if (!$inv): ?>
<div class="sheet r80"><div class="text-center"><b><?= e($biz) ?></b><br><?= e($s['branch']) ?><br><?= e($s['branch_address'] ?: setting('business_address', '')) ?><br><?= e($s['branch_phone'] ?: setting('business_phone', '')) ?></div><div class="dash"></div>
<div>Invoice: <?= e($s['invoice_no']) ?><br>Date: <?= e(fmt_date($s['sale_date'], 'Y-m-d H:i')) ?><br>Cashier: <?= e($s['cashier']) ?><?php if ($s['customer']): ?><br>Customer: <?= e($s['customer']) ?><?php endif; ?></div><?php if ($s['status'] === 'void'): ?><div class="text-center fw-bold">*** VOID ***</div><?php endif; ?><div class="dash"></div>
<table class="l"><?php foreach ($s['items'] as $i): ?><tr><td colspan="2"><?= e($i['name']) ?></td></tr><tr><td><?= (int)$i['qty'] ?> x <?= number_format($i['unit_price'], 2) ?><?= $i['discount'] > 0 ? ' (-' . number_format($i['discount'], 2) . ')' : '' ?></td><td class="text-end"><?= number_format($i['line_total'], 2) ?></td></tr><?php endforeach; ?></table><div class="dash"></div>
<table class="l"><tr><td>Subtotal</td><td class="text-end"><?= number_format($s['subtotal'], 2) ?></td></tr><?php if ($s['discount_total'] > 0): ?><tr><td>Discount</td><td class="text-end">-<?= number_format($s['discount_total'], 2) ?></td></tr><?php endif; ?><?php if ($s['tax_total'] > 0): ?><tr><td>Tax</td><td class="text-end"><?= number_format($s['tax_total'], 2) ?></td></tr><?php endif; ?>
<tr><td><b>TOTAL</b></td><td class="text-end"><b><?= number_format($s['total'], 2) ?></b></td></tr><?php foreach ($s['payments'] as $p): ?><tr><td><?= e(ucwords(str_replace('_', ' ', $p['method']))) ?></td><td class="text-end"><?= number_format($p['amount'], 2) ?></td></tr><?php endforeach; ?>
<?php if ($s['change_amount'] > 0): ?><tr><td>Change</td><td class="text-end"><?= number_format($s['change_amount'], 2) ?></td></tr><?php endif; ?><?php if ($s['credit_amount'] > 0): ?><tr><td>On credit</td><td class="text-end"><?= number_format($s['credit_amount'], 2) ?></td></tr><?php endif; ?></table><div class="dash"></div>
<div class="text-center"><?= e($s['receipt_footer'] ?: setting('receipt_footer', '')) ?></div></div>
<?php else: ?>
<div class="sheet a4"><div class="d-flex justify-content-between"><div><h3 class="mb-0"><?= e($biz) ?></h3><div class="text-muted"><?= e($s['branch_address'] ?: setting('business_address', '')) ?><br><?= e($s['branch_phone'] ?: setting('business_phone', '')) ?></div></div><div class="text-end"><h4>INVOICE</h4><div><?= e($s['invoice_no']) ?><br><?= e(fmt_date($s['sale_date'], 'Y-m-d H:i')) ?></div><?php if ($s['status'] === 'void'): ?><div class="text-danger fw-bold">VOID</div><?php endif; ?></div></div><hr>
<div class="mb-3"><b>Bill to:</b> <?= e($s['customer'] ?: 'Walk-in customer') ?> <?= e($s['customer_phone']) ?></div>
<table class="table table-sm"><thead><tr><th>#</th><th>Item</th><th class="text-end">Qty</th><th class="text-end">Price</th><th class="text-end">Discount</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach ($s['items'] as $n => $i): ?><tr><td><?= $n + 1 ?></td><td><?= e($i['name']) ?></td><td class="text-end"><?= (int)$i['qty'] ?></td><td class="text-end"><?= number_format($i['unit_price'], 2) ?></td><td class="text-end"><?= number_format($i['discount'], 2) ?></td><td class="text-end"><?= number_format($i['line_total'], 2) ?></td></tr><?php endforeach; ?></tbody></table>
<div class="row"><div class="col-6"><b>Payments</b><?php foreach ($s['payments'] as $p): ?><div><?= e(ucwords(str_replace('_', ' ', $p['method']))) ?>: <?= number_format($p['amount'], 2) ?></div><?php endforeach; ?><?php if ($s['credit_amount'] > 0): ?><div>On credit: <?= number_format($s['credit_amount'], 2) ?></div><?php endif; ?></div>
<div class="col-6"><table class="table table-sm"><tr><td>Subtotal</td><td class="text-end"><?= number_format($s['subtotal'], 2) ?></td></tr><tr><td>Discount</td><td class="text-end"><?= number_format($s['discount_total'], 2) ?></td></tr><tr><td>Tax</td><td class="text-end"><?= number_format($s['tax_total'], 2) ?></td></tr><tr class="fw-bold"><td>Total</td><td class="text-end"><?= e(money($s['total'])) ?></td></tr></table></div></div>
<div class="text-center text-muted mt-4"><?= e($s['receipt_footer'] ?: setting('receipt_footer', '')) ?></div></div><?php endif; ?>
<?php if (!empty($auto)): ?><script>window.addEventListener('load',function(){setTimeout(function(){window.print();},300);});</script><?php endif; ?>
</body></html>
