<div class="d-flex justify-content-between mb-3"><div><h4 class="mb-0">Return - <?= e($s['invoice_no']) ?></h4><div class="text-muted"><?= e(fmt_date($s['sale_date'], 'd M Y')) ?> (<?= (int)$age ?> day(s) ago) &middot; <?= e($s['customer'] ?: 'Walk-in') ?></div></div><a class="btn btn-outline-secondary align-self-start" href="<?= url('pos/returns') ?>">Back</a></div>
<?php if ($s['status'] !== 'completed'): ?><div class="alert alert-danger">This sale was voided and cannot be returned.</div><?php else: ?>
<?php if ($age > $days): ?><div class="alert alert-warning">Outside the <?= (int)$days ?>-day return window - manager approval is mandatory.</div><?php endif; ?>
<form method="post" action="<?= url('pos/return_save') ?>" class="needs-validation" novalidate><?= csrf_field() ?><input type="hidden" name="sale_id" value="<?= (int)$s['id'] ?>">
<div class="card mb-3"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>Item</th><th class="text-end">Sold</th><th class="text-end">Returned</th><th class="text-end">Paid (line)</th><th style="width:110px">Return qty</th><th style="width:140px">Condition</th></tr></thead><tbody>
<?php foreach ($items as $i): $rem = $i['qty'] - $i['returned_qty']; ?><tr><td><?= e($i['name']) ?></td><td class="text-end"><?= (int)$i['qty'] ?></td><td class="text-end"><?= (int)$i['returned_qty'] ?></td><td class="text-end"><?= number_format($i['line_total'], 2) ?></td>
<td><input type="number" min="0" max="<?= $rem ?>" value="0" name="qty[<?= (int)$i['id'] ?>]" class="form-control form-control-sm" <?= $rem < 1 ? 'disabled' : '' ?>></td><td><select name="cond[<?= (int)$i['id'] ?>]" class="form-select form-select-sm" <?= $rem < 1 ? 'disabled' : '' ?>><option value="good">Good (restock)</option><option value="damaged">Damaged</option></select></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card card-body mb-3"><div class="row g-3"><div class="col-md-4"><label class="form-label required-star">Reason</label><input name="reason" class="form-control" required minlength="3" maxlength="255"></div>
<div class="col-md-4"><label class="form-label required-star">Refund as</label><select name="refund_method" class="form-select" required><option value="cash">Cash refund</option><option value="card">Card refund</option><?php if ($s['customer_id']): ?><option value="account">Credit to customer account</option><?php endif; ?><option value="exchange">Exchange credit note (use on a new sale)</option></select></div>
<?php if (!$canApprove): ?><div class="col-md-4"><label class="form-label required-star">Manager approval</label><div class="input-group"><input name="approver" class="form-control" placeholder="Manager username" required autocomplete="off"><input type="password" name="approver_pass" class="form-control" placeholder="Password" required autocomplete="new-password"></div></div><?php endif; ?></div></div>
<button class="btn btn-warning once"><i class="bi bi-arrow-return-left"></i> Process return</button></form><?php endif; ?>
