<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><div><h4 class="mb-0"><?= e($s['invoice_no']) ?> <?= badge($s['status']) ?></h4><div class="text-muted"><?= e(fmt_date($s['sale_date'], 'd M Y H:i')) ?> &middot; Cashier <?= e($s['cashier']) ?> &middot; <?= e($s['customer'] ?: 'Walk-in') ?></div></div>
<div class="d-flex gap-1 flex-wrap align-self-start"><?php if (Auth::can('pos.history.reprint')): ?><a class="btn btn-outline-primary btn-sm" target="_blank" href="<?= url('pos/receipt', ['id' => $s['id'], 'reprint' => 1]) ?>"><i class="bi bi-printer"></i> Receipt</a><?php endif; ?><a class="btn btn-outline-secondary btn-sm" target="_blank" href="<?= url('pos/invoice', ['id' => $s['id']]) ?>"><i class="bi bi-file-earmark-text"></i> Invoice</a>
<?php if ($s['status'] === 'completed' && Auth::can('pos.returns.create')): ?><a class="btn btn-outline-warning btn-sm" href="<?= url('pos/return_form', ['sale_id' => $s['id']]) ?>"><i class="bi bi-arrow-return-left"></i> Return</a><?php endif; ?></div></div>
<div class="row g-3"><div class="col-lg-8"><div class="card"><table class="table table-sm mb-0"><thead class="table-light"><tr><th>Item</th><th class="text-end">Qty</th><th class="text-end">Price</th><th class="text-end">Disc</th><th class="text-end">Tax</th><th class="text-end">Total</th><th class="text-end">Returned</th></tr></thead><tbody>
<?php foreach ($s['items'] as $i): ?><tr><td><?= e($i['name']) ?><?= $i['promo_name'] ? ' <span class="badge text-bg-info">' . e($i['promo_name']) . '</span>' : '' ?></td><td class="text-end"><?= (int)$i['qty'] ?></td><td class="text-end"><?= number_format($i['unit_price'], 2) ?></td><td class="text-end"><?= number_format($i['discount'], 2) ?></td><td class="text-end"><?= number_format($i['tax_amount'], 2) ?></td><td class="text-end"><?= number_format($i['line_total'], 2) ?></td><td class="text-end"><?= (int)$i['returned_qty'] ?></td></tr><?php endforeach; ?>
<tr class="fw-bold"><td colspan="5" class="text-end">Total</td><td class="text-end"><?= e(money($s['total'])) ?></td><td></td></tr></tbody></table></div>
<?php if ($returns): ?><div class="card mt-3"><div class="card-header">Returns</div><table class="table table-sm mb-0"><tbody><?php foreach ($returns as $r): ?><tr><td><?= e($r['return_no']) ?></td><td><?= e(fmt_date($r['return_date'], 'd M H:i')) ?></td><td><?= e($r['refund_method']) ?><?= $r['refund_method'] === 'exchange' ? ($r['exchange_used'] ? ' (used)' : ' (balance ' . number_format($r['total_refund'] - $r['credit_used'], 2) . ')') : '' ?></td><td class="text-end"><?= e(money($r['total_refund'])) ?></td><td><?= e($r['reason']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div class="col-lg-4"><div class="card mb-3"><div class="card-header">Payments</div><ul class="list-group list-group-flush"><?php foreach ($s['payments'] as $p): ?><li class="list-group-item d-flex justify-content-between"><span><?= e(ucwords(str_replace('_', ' ', $p['method']))) ?> <small class="text-muted"><?= e($p['reference']) ?></small></span><span><?= number_format($p['amount'], 2) ?></span></li><?php endforeach; ?>
<?php if ($s['change_amount'] > 0): ?><li class="list-group-item d-flex justify-content-between text-muted"><span>Change given</span><span><?= number_format($s['change_amount'], 2) ?></span></li><?php endif; ?><?php if ($s['credit_amount'] > 0): ?><li class="list-group-item d-flex justify-content-between text-danger"><span>On credit</span><span><?= number_format($s['credit_amount'], 2) ?></span></li><?php endif; ?></ul></div>
<?php if (Auth::can('pos.history.reprint')): ?><div class="card mb-3"><div class="card-body"><div class="small text-muted mb-1">Digital receipt link</div><input class="form-control form-control-sm mb-2" readonly onclick="this.select()" value="<?= e((!empty($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . url('receipt/view', ['t' => $s['receipt_token']])) ?>">
<form method="post" action="<?= url('pos/email', ['id' => $s['id']]) ?>" class="input-group input-group-sm"><?= csrf_field() ?><input type="email" name="email" class="form-control" placeholder="Email" value="<?= e($s['customer_email']) ?>" required><button class="btn btn-outline-primary">Email receipt</button></form></div></div><?php endif; ?>
<?php if ($s['status'] === 'completed' && Auth::can('pos.history.void') && !$returns): ?><div class="card border-danger"><div class="card-body"><form method="post" action="<?= url('pos/void') ?>" class="needs-validation" novalidate data-confirm="Void this transaction? Stock and payments will be reversed."><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input name="reason" class="form-control form-control-sm mb-2" placeholder="Reason for void" required minlength="3" maxlength="255"><button class="btn btn-outline-danger btn-sm w-100 once">Void invoice</button></form></div></div><?php elseif ($s['status'] === 'void'): ?><div class="alert alert-danger">Voided: <?= e($s['void_reason']) ?></div><?php endif; ?></div></div>
