<h4 class="mb-3">Register / Session</h4>
<?php if ($s): ?>
<div class="card mb-3"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h5 class="mb-1"><?= e($s['session_no']) ?> <?= badge($s['status']) ?></h5><div class="text-muted">Counter <?= e($s['counter_name']) ?> &middot; opened <?= e(fmt_date($s['opened_at'], 'd M H:i')) ?> &middot; opening cash <?= e(money($s['opening_cash'])) ?></div></div>
<div class="d-flex gap-2 align-self-start"><?php if ($s['status'] === 'open' && Auth::can('pos.sale.create')): ?><a class="btn btn-success" href="<?= url('pos/terminal') ?>"><i class="bi bi-cart4"></i> Open terminal</a><?php endif; ?>
<form method="post" action="<?= url('pos/toggle') ?>"><?= csrf_field() ?><button class="btn btn-outline-warning"><?= $s['status'] === 'open' ? 'Suspend' : 'Resume' ?></button></form></div></div>
<hr><div class="row g-3"><div class="col-md-3"><div class="text-muted small">Sales (completed)</div><div class="stat-value"><?= (int)$summary['count'] ?></div></div><div class="col-md-3"><div class="text-muted small">Sales value</div><div class="stat-value"><?= e(money($summary['total'])) ?></div></div><div class="col-md-3"><div class="text-muted small">Expected cash in drawer</div><div class="stat-value"><?= e(money($summary['cash_sales'])) ?></div></div>
<div class="col-md-3"><div class="text-muted small">By method</div><?php foreach ($summary['methods'] as $m): ?><div class="small"><?= e(ucwords(str_replace('_', ' ', $m['method']))) ?>: <?= e(money($m['amt'])) ?></div><?php endforeach; ?></div></div></div></div>
<div class="card mb-3"><div class="card-header">Close shift &amp; count cash</div><div class="card-body"><form method="post" action="<?= url('pos/close') ?>" class="row g-2 needs-validation" novalidate data-confirm="Close the register? You will not be able to sell until you open a new session."><?= csrf_field() ?>
<div class="col-md-3"><label class="form-label small">Counted cash in drawer</label><input type="number" name="counted_cash" min="0" step="0.01" class="form-control" required></div><div class="col-md-6"><label class="form-label small">Notes</label><input name="notes" maxlength="255" class="form-control"></div><div class="col-md-3 align-self-end"><button class="btn btn-danger w-100 once">Close register</button></div></form>
<div class="form-text">Expected cash is calculated by the system (opening cash + cash sales - cash refunds). Any difference is recorded as the cash variance.</div></div></div>
<?php else: ?>
<div class="card mb-3"><div class="card-header">Open register</div><div class="card-body"><form method="post" action="<?= url('pos/open') ?>" class="row g-2 needs-validation" novalidate><?= csrf_field() ?>
<div class="col-md-4"><label class="form-label small">Counter</label><select name="counter_id" class="form-select" required><option value="">-- Select --</option><?php foreach ($counters as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $c['busy'] ? 'disabled' : '' ?>><?= e($c['branch'] . ' / ' . $c['name']) ?><?= $c['busy'] ? ' (in use)' : '' ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label small">Opening cash</label><input type="number" name="opening_cash" min="0" step="0.01" value="0" class="form-control" required></div><div class="col-md-3 align-self-end"><button class="btn btn-primary once"><i class="bi bi-door-open"></i> Start shift</button></div></form></div></div>
<?php endif; ?>
<div class="card"><div class="card-header">Recent sessions</div><div class="table-responsive"><table class="table table-sm mb-0"><thead class="table-light"><tr><th>Session</th><th>Cashier</th><th>Opened</th><th>Closed</th><th class="text-end">Expected</th><th class="text-end">Counted</th><th class="text-end">Variance</th><th>Status</th></tr></thead><tbody>
<?php foreach ($recent as $r): ?><tr><td><?= e($r['session_no']) ?></td><td><?= e($r['full_name']) ?></td><td><?= e(fmt_date($r['opened_at'], 'd M H:i')) ?></td><td><?= e(fmt_date($r['closed_at'], 'd M H:i')) ?></td><td class="text-end"><?= $r['expected_cash'] !== null ? number_format($r['expected_cash'], 2) : '' ?></td><td class="text-end"><?= $r['counted_cash'] !== null ? number_format($r['counted_cash'], 2) : '' ?></td><td class="text-end <?= (float)$r['variance'] != 0 ? 'text-danger' : '' ?>"><?= $r['variance'] !== null ? number_format($r['variance'], 2) : '' ?></td><td><?= badge($r['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
