<div class="d-flex justify-content-between mb-3"><h4>Inventory Alerts</h4><form method="get"><input type="hidden" name="r" value="alerts/index"><select name="warehouse" class="form-select" data-autosubmit><option value="">All warehouses</option><?php foreach ($warehouses as $w): ?><option value="<?= (int)$w['id'] ?>" <?= $wh == $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></form></div>
<div class="row g-3 mb-3"><?php foreach ([['Low stock', count($al['low']), 'warning'], ['Out of stock', count($al['out']), 'danger'], ['Overstock', count($al['over']), 'info']] as [$l, $n, $c]): ?><div class="col-md-4"><div class="card border-<?= $c ?>"><div class="card-body"><div class="text-muted small"><?= $l ?></div><div class="stat-value"><?= $n ?></div></div></div></div><?php endforeach; ?></div>
<form method="post" action="<?= url('alerts/request') ?>"><?= csrf_field() ?>
<?php if (Auth::can('inventory.alerts.request')): ?><div class="card card-body mb-3"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small mb-0">Replenish warehouse</label><select name="warehouse_id" class="form-select form-select-sm" required><?php foreach ($warehouses as $w): ?><option value="<?= (int)$w['id'] ?>" <?= $wh == $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label small mb-0">Create draft PO for supplier (optional)</label><select name="supplier_id" class="form-select form-select-sm"><option value="">- Only create purchase requests -</option><?php foreach ($suppliers as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['name']) ?></option><?php endforeach; ?></select></div><div class="col-auto"><button class="btn btn-primary btn-sm once"><i class="bi bi-cart-plus"></i> Create for selected</button></div></div></div><?php endif; ?>
<?php foreach (['out' => ['Out of stock', 'danger'], 'low' => ['Low stock (at or below reorder level)', 'warning']] as $k => [$title, $c]): ?><div class="card mb-3"><div class="card-header"><span class="badge text-bg-<?= $c ?>"><?= e($title) ?></span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th style="width:40px"></th><th>SKU</th><th>Product</th><th class="text-end">On hand</th><th class="text-end">Reorder at</th><th class="text-end">Pending request</th><th style="width:120px">Order qty</th></tr></thead><tbody>
<?php foreach ($al[$k] as $r): $sug = max(1, ($r['reorder_level'] * 2) - $r['qty']); ?><tr><td><input type="checkbox" class="form-check-input" name="sel[<?= (int)$r['id'] ?>]" value="1"></td><td><?= e($r['sku']) ?></td><td><?= e($r['name']) ?></td><td class="text-end"><?= (int)$r['qty'] ?></td><td class="text-end"><?= (int)$r['reorder_level'] ?></td><td class="text-end"><?= (int)($open[$r['id']] ?? 0) ?></td><td><input type="number" min="1" name="qty[<?= (int)$r['id'] ?>]" value="<?= $sug ?>" class="form-control form-control-sm"></td></tr><?php endforeach; ?>
<?php if (!$al[$k]): ?><tr><td colspan="7" class="text-center text-muted py-2">None.</td></tr><?php endif; ?></tbody></table></div></div><?php endforeach; ?></form>
<?php if ($al['over']): ?><div class="card mb-3"><div class="card-header"><span class="badge text-bg-info">Overstock</span></div><table class="table table-sm mb-0"><tbody><?php foreach ($al['over'] as $r): ?><tr><td><?= e($r['sku']) ?></td><td><?= e($r['name']) ?></td><td class="text-end"><?= (int)$r['qty'] ?> / max <?= (int)$r['max_stock'] ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<div class="card"><div class="card-header">Open purchase requests</div><table class="table table-sm mb-0 align-middle"><tbody><?php foreach ($requests as $r): ?><tr><td><?= e($r['sku'] . ' ' . $r['name']) ?></td><td><?= e($r['wname']) ?></td><td class="text-end"><?= (int)$r['qty'] ?></td><td><?= badge($r['status']) ?></td><td><?= $r['po_id'] ? '<a href="' . e(url('purchasing/view', ['id' => $r['po_id']])) . '">PO</a>' : '' ?></td><td class="text-end"><?php if (Auth::can('inventory.alerts.request')): ?><form method="post" action="<?= url('alerts/resolve') ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-success">Mark resolved</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$requests): ?><tr><td class="text-muted text-center py-2">None.</td></tr><?php endif; ?></tbody></table></div>
