<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><div><h4 class="mb-0"><?= e($s['st_no']) ?> <?= badge($s['status']) ?></h4><div class="text-muted"><?= e($s['wname']) ?> <?= $s['cname'] ? '&middot; ' . e($s['cname']) : '' ?></div></div>
<div class="d-flex gap-1 align-self-start flex-wrap"><a class="btn btn-outline-secondary btn-sm" href="<?= url('stocktake/count', ['id' => $s['id']] + (input('only') ? [] : ['only' => 'variance'])) ?>"><?= input('only') ? 'Show all' : 'Variances only' ?></a>
<a class="btn btn-outline-secondary btn-sm" href="<?= url('stocktake/report', ['id' => $s['id']]) ?>"><i class="bi bi-file-earmark-text"></i> Report</a>
<?php if (Auth::can('inventory.stocktake.approve') && $s['status'] === 'pending_approval'): foreach (['approve' => ['success', 'Approve & adjust stock'], 'reopen' => ['outline-warning', 'Reopen counting']] as $d => [$c, $l]): ?><form method="post" action="<?= url('stocktake/decide') ?>" data-confirm="<?= e($l) ?>?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="decision" value="<?= $d ?>"><button class="btn btn-sm btn-<?= $c ?>"><?= $l ?></button></form><?php endforeach; endif; ?>
<?php if (Auth::can('inventory.stocktake.approve') && in_array($s['status'], ['counting', 'pending_approval'], true)): ?><form method="post" action="<?= url('stocktake/decide') ?>" data-confirm="Cancel this stocktake?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="decision" value="cancel"><button class="btn btn-sm btn-outline-danger">Cancel</button></form><?php endif; ?></div></div>
<form method="post"><?= csrf_field() ?><div class="card"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>SKU</th><th>Product</th><th class="text-end">System</th><th style="width:130px">Counted</th><th class="text-end">Variance</th></tr></thead><tbody>
<?php foreach ($items as $i): ?><tr class="<?= $i['variance'] ? 'table-warning' : '' ?>"><td><?= e($i['sku']) ?></td><td><?= e($i['name']) ?></td><td class="text-end"><?= (int)$i['system_qty'] ?></td>
<td><?php if ($s['status'] === 'counting' && Auth::can('inventory.stocktake.create')): ?><input type="number" min="0" step="1" name="counted[<?= (int)$i['id'] ?>]" value="<?= $i['counted_qty'] ?>" class="form-control form-control-sm"><?php else: echo $i['counted_qty'] !== null ? (int)$i['counted_qty'] : ''; endif; ?></td>
<td class="text-end <?= $i['variance'] < 0 ? 'text-danger' : ($i['variance'] > 0 ? 'text-success' : '') ?>"><?= $i['variance'] !== null ? ($i['variance'] > 0 ? '+' : '') . (int)$i['variance'] : '' ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php if ($s['status'] === 'counting' && Auth::can('inventory.stocktake.create')): ?><div class="mt-3"><button class="btn btn-primary"><i class="bi bi-save"></i> Save counts</button> <button class="btn btn-success" name="submit_for_approval" value="1" data-x="1">Save &amp; submit for approval</button></div><?php endif; ?></form>
