<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><div><h4 class="mb-0"><?= e($po['po_no']) ?> <?= badge($po['status']) ?></h4><div class="text-muted"><?= e($po['supplier']) ?> &rarr; <?= e($po['warehouse']) ?> &middot; <?= e($po['order_date']) ?></div></div>
<div class="d-flex gap-1 flex-wrap align-self-start">
<?php $btn = function ($to, $label, $cls, $perm, $ok) use ($po) { if (!Auth::can($perm) || !in_array($po['status'], $ok, true)) return; ?><form method="post" action="<?= url('purchasing/status') ?>" data-confirm="<?= e($label) ?>?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$po['id'] ?>"><input type="hidden" name="to" value="<?= $to ?>"><button class="btn btn-<?= $cls ?>"><?= e($label) ?></button></form><?php };
if ($po['status'] === 'draft' && Auth::can('inventory.purchasing.create')): ?><a class="btn btn-outline-primary" href="<?= url('purchasing/form', ['id' => $po['id']]) ?>"><i class="bi bi-pencil"></i> Edit</a><?php endif;
$btn('submitted', 'Submit', 'primary', 'inventory.purchasing.create', ['draft']); $btn('approved', 'Approve', 'success', 'inventory.purchasing.approve', ['submitted']); $btn('cancelled', 'Cancel PO', 'outline-danger', 'inventory.purchasing.approve', ['draft', 'submitted', 'approved']);
if (in_array($po['status'], ['approved', 'partial'], true) && Auth::can('inventory.purchasing.receive')): ?><a class="btn btn-success" href="<?= url('purchasing/receive', ['id' => $po['id']]) ?>"><i class="bi bi-box-arrow-in-down"></i> Receive goods</a><?php endif; ?>
<a class="btn btn-outline-secondary" href="javascript:window.print()"><i class="bi bi-printer"></i></a></div></div>
<div class="card mb-3"><table class="table table-sm mb-0"><thead class="table-light"><tr><th>SKU</th><th>Product</th><th class="text-end">Ordered</th><th class="text-end">Received</th><th class="text-end">Price</th><th class="text-end">Total</th></tr></thead><tbody>
<?php foreach ($items as $i): ?><tr><td><?= e($i['sku']) ?></td><td><?= e($i['name']) ?></td><td class="text-end"><?= (int)$i['qty'] ?></td><td class="text-end"><?= (int)$i['received_qty'] ?></td><td class="text-end"><?= number_format($i['price'], 2) ?></td><td class="text-end"><?= number_format($i['qty'] * $i['price'], 2) ?></td></tr><?php endforeach; ?>
<tr class="fw-bold"><td colspan="5" class="text-end">Total</td><td class="text-end"><?= e(money($po['total'])) ?></td></tr></tbody></table></div>
<?php if ($grns): ?><div class="card"><div class="card-header">Goods received notes</div><ul class="list-group list-group-flush"><?php foreach ($grns as $g): ?><li class="list-group-item"><a href="<?= url('purchasing/grn', ['id' => $g['id']]) ?>"><?= e($g['grn_no']) ?></a> &middot; <?= e($g['received_date']) ?> <?= $g['invoice_id'] ? '<span class="badge text-bg-success">Invoiced</span>' : '<span class="badge text-bg-warning">Not invoiced</span>' ?></li><?php endforeach; ?></ul></div><?php endif; ?>
