<?php $qs = array_filter(['warehouse' => $wh, 'q' => $q, 'filter' => $flt]); ?>
<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><h4 class="mb-0">Stock Levels <span class="badge text-bg-light"><?= (int)$total ?></span></h4><div>
<a class="btn btn-outline-secondary" href="<?= url('stock/index', $qs + ['export' => 'csv']) ?>"><i class="bi bi-download"></i> CSV</a>
<?php if (Auth::can('inventory.stock.adjust')): ?><a class="btn btn-primary" href="<?= url('stock/adjust') ?>"><i class="bi bi-sliders"></i> Adjust stock</a><?php endif; ?></div></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="stock/index"><div class="col-md-3"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="Search..."></div>
<div class="col-md-3"><select class="form-select" name="warehouse" data-autosubmit><option value="">All warehouses</option><?php foreach ($warehouses as $w): ?><option value="<?= (int)$w['id'] ?>" <?= $wh == $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><select class="form-select" name="filter" data-autosubmit><option value="">All</option><option value="low" <?= $flt === 'low' ? 'selected' : '' ?>>Low stock</option><option value="out" <?= $flt === 'out' ? 'selected' : '' ?>>Out of stock</option><option value="damaged" <?= $flt === 'damaged' ? 'selected' : '' ?>>Has damaged</option></select></div><div class="col-auto"><button class="btn btn-outline-secondary"><i class="bi bi-search"></i></button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>SKU</th><th>Product</th><th class="text-end">On hand</th><th class="text-end">Reserved</th><th class="text-end">Available</th><th class="text-end">Damaged</th><th class="text-end">Reorder</th><th class="text-end">Value (cost)</th></tr></thead><tbody>
<?php foreach ($rows as $r): $av = $r['qty'] - $r['reserved']; ?><tr><td><?= e($r['sku']) ?></td><td><?= e($r['name']) ?></td><td class="text-end"><span class="badge text-bg-<?= $r['qty'] <= 0 ? 'danger' : ($r['qty'] <= $r['reorder_level'] ? 'warning' : 'success') ?>"><?= (int)$r['qty'] ?></span></td><td class="text-end"><?= (int)$r['reserved'] ?></td><td class="text-end"><?= (int)$av ?></td><td class="text-end"><?= (int)$r['damaged'] ?></td><td class="text-end"><?= (int)$r['reorder_level'] ?></td><td class="text-end"><?= number_format($r['qty'] * $r['cost_price'], 2) ?></td></tr><?php endforeach; ?>
<?php if (!$rows): ?><tr><td colspan="8" class="text-center text-muted py-3">No products.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if ($pages > 1): ?><nav class="mt-3"><ul class="pagination pagination-sm"><?php for ($i = max(1, $page - 4); $i <= min($pages, $page + 4); $i++): ?><li class="page-item <?= $i === $page ? 'active' : '' ?>"><a class="page-link" href="<?= url('stock/index', $qs + ['page' => $i]) ?>"><?= $i ?></a></li><?php endfor; ?></ul></nav><?php endif; ?>
