<div class="d-flex flex-wrap justify-content-between mb-3 gap-2"><div><h4 class="mb-0"><?= e($s['name']) ?> <small class="text-muted"><?= e($s['code']) ?></small></h4><div class="text-muted"><?= e($s['contact_person']) ?> <?= e($s['phone']) ?> <?= e($s['email']) ?></div></div>
<div><a class="btn btn-outline-secondary" href="<?= url('supplier/statement', ['id' => $s['id']]) ?>"><i class="bi bi-file-text"></i> Statement</a> <a class="btn btn-outline-secondary" href="<?= url('crud/list', ['e' => 'suppliers']) ?>">Back</a></div></div>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Outstanding balance</div><div class="stat-value <?= $balance > 0 ? 'text-danger' : '' ?>"><?= e(money($balance)) ?></div></div></div></div>
<div class="col-md-9"><?php if (Auth::can('admin.suppliers.payment')): ?><div class="card"><div class="card-body"><form method="post" action="<?= url('supplier/payment', ['id' => $s['id']]) ?>" class="row g-2 needs-validation" novalidate><?= csrf_field() ?>
<div class="col-md-2"><input type="number" step="0.01" min="0.01" name="amount" class="form-control" placeholder="Amount" required></div>
<div class="col-md-2"><select name="method" class="form-select"><?php foreach (payment_methods() as $k => $l): ?><option value="<?= $k ?>"><?= $l ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><input type="date" name="paid_date" value="<?= date('Y-m-d') ?>" max="<?= date('Y-m-d') ?>" class="form-control" required></div>
<div class="col-md-3"><select name="invoice_id" class="form-select"><option value="">General payment</option><?php foreach ($invoices as $i): if ($i['due'] > 0.004): ?><option value="<?= (int)$i['id'] ?>"><?= e($i['inv_no'] . ' (due ' . number_format($i['due'], 2) . ')') ?></option><?php endif; endforeach; ?></select></div>
<div class="col-md-3"><input name="reference" class="form-control" placeholder="Reference" maxlength="80"></div><div class="col-12"><button class="btn btn-success btn-sm once"><i class="bi bi-cash"></i> Record payment</button></div></form></div></div><?php endif; ?></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card"><div class="card-header">Purchase orders</div><table class="table table-sm mb-0"><tbody><?php foreach ($pos as $p): ?><tr><td><a href="<?= url('purchasing/view', ['id' => $p['id']]) ?>"><?= e($p['po_no']) ?></a></td><td><?= e($p['order_date']) ?></td><td class="text-end"><?= e(money($p['total'])) ?></td><td><?= badge($p['status']) ?></td></tr><?php endforeach; ?><?php if (!$pos): ?><tr><td class="text-muted text-center">None</td></tr><?php endif; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">Purchase invoices</div><table class="table table-sm mb-0"><tbody><?php foreach ($invoices as $i): ?><tr><td><?= e($i['inv_no']) ?></td><td><?= e($i['invoice_date']) ?></td><td class="text-end"><?= e(money($i['total'])) ?></td><td><?= badge($i['status']) ?></td></tr><?php endforeach; ?><?php if (!$invoices): ?><tr><td class="text-muted text-center">None</td></tr><?php endif; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">Payments</div><table class="table table-sm mb-0"><tbody><?php foreach ($payments as $p): ?><tr><td><?= e($p['pay_no']) ?></td><td><?= e($p['paid_date']) ?></td><td><?= e($p['inv_no']) ?></td><td class="text-end"><?= e(money($p['amount'])) ?></td></tr><?php endforeach; ?><?php if (!$payments): ?><tr><td class="text-muted text-center">None</td></tr><?php endif; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">Supplied products</div><table class="table table-sm mb-0 align-middle"><tbody><?php foreach ($products as $p): ?><tr><td><?= e($p['sku']) ?></td><td><?= e($p['name']) ?></td><td class="text-end"><?= $p['last_price'] !== null ? e(money($p['last_price'])) : '' ?></td>
<td class="text-end"><?php if (Auth::can('admin.suppliers.products')): ?><form method="post" action="<?= url('supplier/unassign', ['id' => $s['id']]) ?>" class="d-inline"><?= csrf_field() ?><input type="hidden" name="product_id" value="<?= (int)$p['product_id'] ?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-x"></i></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table>
<?php if (Auth::can('admin.suppliers.products')): ?><form method="post" action="<?= url('supplier/assign', ['id' => $s['id']]) ?>" class="card-body row g-2 border-top"><?= csrf_field() ?><div class="col-md-5"><select name="product_id" class="form-select form-select-sm" required><option value="">Product...</option><?php foreach ($allProducts as $p): ?><option value="<?= (int)$p['id'] ?>"><?= e($p['sku'] . ' ' . $p['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><input name="supplier_sku" class="form-control form-control-sm" placeholder="Supplier SKU"></div><div class="col-md-2"><input type="number" step="0.01" min="0" name="last_price" class="form-control form-control-sm" placeholder="Price"></div><div class="col-md-2"><button class="btn btn-sm btn-primary w-100">Assign</button></div></form><?php endif; ?></div></div></div>
