<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Barcode Labels</h4>
<?php if ($missing && Auth::can('inventory.products.edit')): ?><form method="post" action="<?= url('products/assign') ?>" data-confirm="Generate barcodes for <?= (int)$missing ?> product(s) without one?"><?= csrf_field() ?><button class="btn btn-warning"><i class="bi bi-magic"></i> Generate <?= (int)$missing ?> missing barcode(s)</button></form><?php endif; ?></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="products/labels"><div class="col-md-4"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="Name, SKU, barcode, ISBN"></div>
<div class="col-md-2"><select name="type" class="form-select" data-autosubmit><option value="">All types</option><?php foreach (['book' => 'Books', 'stationery' => 'Stationery', 'other' => 'Other'] as $k => $l): ?><option value="<?= $k ?>" <?= $type === $k ? 'selected' : '' ?>><?= $l ?></option><?php endforeach; ?></select></div>
<div class="col-auto align-self-center"><div class="form-check"><input class="form-check-input" type="checkbox" name="nobarcode" value="1" id="nb" <?= input('nobarcode') ? 'checked' : '' ?> onchange="this.form.submit()"><label class="form-check-label" for="nb">Without barcode only</label></div></div><div class="col-auto"><button class="btn btn-outline-secondary"><i class="bi bi-search"></i></button></div></form>
<form method="post" action="<?= url('products/print') ?>" target="_blank"><?= csrf_field() ?>
<div class="card mb-3"><div class="card-body row g-2 align-items-end"><div class="col-auto"><label class="form-label small mb-0">Label size</label><select name="size" class="form-select form-select-sm"><option value="small">Small (38 x 25 mm)</option><option value="medium" selected>Medium (50 x 30 mm)</option><option value="large">Large (70 x 40 mm)</option></select></div>
<div class="col-auto"><div class="form-check"><input class="form-check-input" type="checkbox" name="name" value="1" id="pn" checked><label class="form-check-label" for="pn">Name</label></div></div><div class="col-auto"><div class="form-check"><input class="form-check-input" type="checkbox" name="price" value="1" id="pp" checked><label class="form-check-label" for="pp">Price</label></div></div>
<div class="col-auto"><button type="button" class="btn btn-sm btn-outline-secondary" onclick="document.querySelectorAll('.lq').forEach(i=>{if(!i.disabled)i.value=1})">Set all to 1</button> <button type="button" class="btn btn-sm btn-outline-secondary" onclick="document.querySelectorAll('.lq').forEach(i=>i.value=0)">Clear</button></div>
<div class="col-auto ms-auto"><button class="btn btn-primary"><i class="bi bi-printer"></i> Print selected labels</button></div></div></div>
<div class="card"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th style="width:90px">Labels</th><th>SKU</th><th>Product</th><th>Barcode</th><th class="text-end">Price</th></tr></thead><tbody>
<?php foreach ($products as $p): $has = $p['barcode'] !== null && $p['barcode'] !== ''; ?><tr><td><input type="number" min="0" max="200" value="0" name="qty[<?= (int)$p['id'] ?>]" class="form-control form-control-sm lq" <?= $has ? '' : 'disabled' ?>></td><td><?= e($p['sku']) ?></td><td><?= e($p['name']) ?></td>
<td><?= $has ? '<a href="' . e(url('products/label', ['id' => $p['id']])) . '">' . e($p['barcode']) . '</a>' : '<span class="badge text-bg-warning">none</span>' ?></td><td class="text-end"><?= e(money($p['selling_price'])) ?></td></tr><?php endforeach; ?>
<?php if (!$products): ?><tr><td colspan="5" class="text-center text-muted py-3">No products.</td></tr><?php endif; ?></tbody></table></div></div></form>
