<div class="d-flex justify-content-between mb-3"><div><h4 class="mb-0"><?= e($c['name']) ?> <small class="text-muted"><?= e($c['code']) ?></small></h4><div class="text-muted"><?= e($c['phone']) ?> <?= e($c['email']) ?> &middot; <?= e($c['group_name']) ?></div></div><a class="btn btn-outline-secondary align-self-start" href="<?= url('crud/list', ['e' => 'customers']) ?>">Back</a></div>
<div class="row g-3 mb-3">
<div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Outstanding balance</div><div class="stat-value <?= $balance > 0 ? 'text-danger' : '' ?>"><?= e(money($balance)) ?></div></div></div></div>
<div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Credit limit</div><div class="stat-value"><?= e(money($c['credit_limit'])) ?></div></div></div></div>
<div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Loyalty points</div><div class="stat-value"><?= (int)$c['loyalty_points'] ?></div></div></div></div>
<div class="col-md-3"><?php if (Auth::can('admin.customers.payment') && $balance > 0): ?><div class="card"><div class="card-body"><form method="post" action="<?= url('customer/payment', ['id' => $c['id']]) ?>" class="needs-validation" novalidate><?= csrf_field() ?>
<div class="input-group input-group-sm mb-1"><input type="number" name="amount" step="0.01" min="0.01" max="<?= $balance ?>" class="form-control" placeholder="Receive payment" required><select name="method" class="form-select"><?php foreach (payment_methods() as $k => $l): ?><option value="<?= $k ?>"><?= $l ?></option><?php endforeach; ?></select></div><button class="btn btn-success btn-sm w-100 once">Record receipt</button></form></div></div><?php endif; ?></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card"><div class="card-header">Purchase history</div><table class="table table-sm mb-0"><tbody>
<?php foreach ($sales as $s): ?><tr><td><a href="<?= url('pos/sale', ['id' => $s['id']]) ?>"><?= e($s['invoice_no']) ?></a></td><td><?= e(fmt_date($s['sale_date'], 'd M Y')) ?></td><td class="text-end"><?= e(money($s['total'])) ?></td><td><?= badge($s['status']) ?></td></tr><?php endforeach; ?><?php if (!$sales): ?><tr><td class="text-muted text-center">No purchases.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card mb-3"><div class="card-header">Payments received</div><table class="table table-sm mb-0"><tbody><?php foreach ($payments as $p): ?><tr><td><?= e(fmt_date($p['created_at'], 'd M Y')) ?></td><td><?= e($p['method']) ?></td><td class="text-end"><?= e(money($p['amount'])) ?></td></tr><?php endforeach; ?><?php if (!$payments): ?><tr><td class="text-muted text-center">None.</td></tr><?php endif; ?></tbody></table></div>
<div class="card"><div class="card-header">Loyalty</div><table class="table table-sm mb-0"><tbody><?php foreach ($loyalty as $l): ?><tr><td><?= e(fmt_date($l['created_at'], 'd M Y')) ?></td><td><?= e($l['reason']) ?></td><td class="text-end"><?= (int)$l['points'] > 0 ? '+' : '' ?><?= (int)$l['points'] ?></td></tr><?php endforeach; ?></tbody></table>
<?php if (Auth::can('admin.customers.loyalty')): ?><form method="post" action="<?= url('customer/loyalty', ['id' => $c['id']]) ?>" class="card-body border-top row g-2 needs-validation" novalidate><?= csrf_field() ?><div class="col-3"><input type="number" name="points" class="form-control form-control-sm" placeholder="+/- pts" required></div><div class="col-6"><input name="reason" maxlength="160" class="form-control form-control-sm" placeholder="Reason" required></div><div class="col-3"><button class="btn btn-sm btn-primary w-100">Adjust</button></div></form><?php endif; ?></div></div></div>
