<?php $qs = array_filter(['report' => $key, 'from' => $from, 'to' => $to, 'q' => $q, 'compare' => input('compare')]); $isNum = fn($i) => in_array($i, $numCols, true); $f = fn($v, $i) => ($isNum($i) && is_numeric($v)) ? ((string)(float)$v === (string)(int)(float)$v && !str_contains((string)$v, '.') ? number_format((float)$v, 0) : number_format((float)$v, 2)) : $v; ?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-3 no-print gap-2"><h4 class="mb-0"><?= e($title) ?></h4><div class="d-flex gap-1"><?php if (Auth::can('admin.reports.export')): ?><a class="btn btn-sm btn-outline-secondary" href="<?= url('reports/view', $qs + ['export' => 'csv']) ?>"><i class="bi bi-filetype-csv"></i> CSV</a><a class="btn btn-sm btn-outline-secondary" href="<?= url('reports/view', $qs + ['export' => 'pdf']) ?>"><i class="bi bi-file-earmark-pdf"></i> PDF</a><button class="btn btn-sm btn-outline-secondary" onclick="window.print()"><i class="bi bi-printer"></i> Print</button><?php endif; ?><a class="btn btn-sm btn-outline-secondary" href="<?= url('reports/index') ?>">All reports</a></div></div>
<form class="row g-2 mb-3 no-print" method="get"><input type="hidden" name="r" value="reports/view"><input type="hidden" name="report" value="<?= e($key) ?>">
<?php if ($period): ?><div class="col-auto"><input type="date" name="from" class="form-control" value="<?= e($from) ?>"></div><div class="col-auto"><input type="date" name="to" class="form-control" value="<?= e($to) ?>"></div><div class="col-auto align-self-center"><div class="form-check"><input class="form-check-input" type="checkbox" name="compare" value="1" id="cmp" <?= input('compare') ? 'checked' : '' ?>><label class="form-check-label" for="cmp">Compare with previous period</label></div></div><?php endif; ?>
<div class="col-md-3"><input name="q" class="form-control" placeholder="Search within report" value="<?= e($q) ?>"></div><div class="col-auto"><button class="btn btn-primary">Apply</button></div></form>
<p class="text-muted"><?= $period ? e("$from to $to") : 'As at ' . date('Y-m-d H:i') ?> &middot; <?= count($rows) ?> row(s)</p>
<?php if ($cmp && $cmp['totals'] && $totals): ?><div class="card mb-3"><div class="card-header">Previous period (<?= e($cmp['from'] . ' to ' . $cmp['to']) ?>)</div><div class="table-responsive"><table class="table table-sm mb-0"><thead class="table-light"><tr><?php foreach ($headers as $i => $h): if (!$isNum($i)) continue; ?><th class="text-end"><?= e($h) ?></th><?php endforeach; ?></tr></thead><tbody>
<tr><?php foreach ($headers as $i => $h): if (!$isNum($i)) continue; ?><td class="text-end"><?= number_format((float)($totals[$i] ?? 0), 2) ?> <small class="text-muted">now</small></td><?php endforeach; ?></tr><tr><?php foreach ($headers as $i => $h): if (!$isNum($i)) continue; ?><td class="text-end"><?= number_format((float)($cmp['totals'][$i] ?? 0), 2) ?> <small class="text-muted">prev</small></td><?php endforeach; ?></tr>
<tr><?php foreach ($headers as $i => $h): if (!$isNum($i)) continue; $a = (float)($totals[$i] ?? 0); $b = (float)($cmp['totals'][$i] ?? 0); $p = $b != 0 ? ($a - $b) / abs($b) * 100 : null; ?><td class="text-end <?= $p !== null && $p < 0 ? 'text-danger' : 'text-success' ?>"><?= $p === null ? 'n/a' : ($p >= 0 ? '+' : '') . number_format($p, 1) . '%' ?></td><?php endforeach; ?></tr></tbody></table></div></div><?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table table-sm table-striped mb-0"><thead class="table-light"><tr><?php foreach ($headers as $i => $h): ?><th class="<?= $isNum($i) ? 'text-end' : '' ?>"><?= e($h) ?></th><?php endforeach; ?></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><?php foreach ($r as $i => $v): ?><td class="<?= $isNum($i) ? 'text-end' : '' ?>"><?= e($f($v, $i)) ?></td><?php endforeach; ?></tr><?php endforeach; ?>
<?php if (!$rows): ?><tr><td colspan="<?= count($headers) ?>" class="text-center text-muted py-3">No data.</td></tr><?php endif; ?>
<?php if ($totals): ?><tr class="fw-bold table-light"><?php foreach ($totals as $i => $v): ?><td class="<?= $isNum($i) ? 'text-end' : '' ?>"><?= e($v === '' ? '' : (is_numeric($v) ? number_format((float)$v, 2) : $v)) ?></td><?php endforeach; ?></tr><?php endif; ?></tbody></table></div></div>
