<h4 class="mb-3">Cash Drawer &amp; Reconciliation</h4>
<div class="card mb-3"><div class="card-header">Register sessions</div><div class="table-responsive"><table class="table table-sm mb-0 align-middle"><thead class="table-light"><tr><th>Session</th><th>Cashier</th><th>Branch / Counter</th><th>Opened</th><th class="text-end">Opening</th><th class="text-end">Expected</th><th class="text-end">Counted</th><th class="text-end">Variance</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($sessions as $s): ?><tr><td><?= e($s['session_no']) ?></td><td><?= e($s['full_name']) ?></td><td><?= e($s['branch'] . ' / ' . $s['counter']) ?></td><td><?= e(fmt_date($s['opened_at'], 'd M H:i')) ?></td><td class="text-end"><?= number_format($s['opening_cash'], 2) ?></td><td class="text-end"><?= $s['expected_cash'] !== null ? number_format($s['expected_cash'], 2) : '' ?></td><td class="text-end"><?= $s['counted_cash'] !== null ? number_format($s['counted_cash'], 2) : '' ?></td>
<td class="text-end <?= (float)$s['variance'] != 0 ? 'text-danger fw-bold' : '' ?>"><?= $s['variance'] !== null ? number_format($s['variance'], 2) : '' ?></td><td><?= badge($s['status']) ?></td>
<td><?php if ($s['status'] === 'closed' && Auth::can('admin.finance.reconcile')): ?><form method="post" action="<?= url('finance/reconcile') ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><button class="btn btn-sm btn-outline-success">Reconcile</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$sessions): ?><tr><td colspan="10" class="text-center text-muted py-3">No sessions yet.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="row g-3"><?php if (Auth::can('admin.finance.cash')): ?><div class="col-md-5"><div class="card card-body"><h6>Record cash adjustment</h6><form method="post" action="<?= url('finance/adjust') ?>" class="row g-2 needs-validation" novalidate><?= csrf_field() ?>
<div class="col-6"><select name="branch_id" class="form-select" required><?php foreach ($branches as $b): ?><option value="<?= (int)$b['id'] ?>"><?= e($b['name']) ?></option><?php endforeach; ?></select></div><div class="col-6"><select name="type" class="form-select"><option value="in">Cash in</option><option value="out">Cash out</option></select></div>
<div class="col-6"><input type="number" name="amount" step="0.01" min="0.01" class="form-control" placeholder="Amount" required></div><div class="col-12"><input name="reason" class="form-control" placeholder="Reason" maxlength="255" required></div><div class="col-12"><button class="btn btn-primary once">Record</button></div></form></div></div><?php endif; ?>
<div class="col-md-7"><div class="card"><div class="card-header">Recent adjustments</div><table class="table table-sm mb-0 small"><tbody><?php foreach ($adj as $a): ?><tr><td><?= e(fmt_date($a['created_at'], 'd M H:i')) ?></td><td><?= e($a['branch']) ?></td><td><?= $a['type'] === 'in' ? 'In' : 'Out' ?></td><td class="text-end"><?= number_format($a['amount'], 2) ?></td><td><?= e($a['reason']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
