<?php $qs = array_filter(['type' => input('type'), 'method' => input('method'), 'branch' => input('branch'), 'direction' => input('direction'), 'from' => $from, 'to' => $to]); ?>
<div class="d-flex justify-content-between mb-3"><h4>Financial Transactions</h4><a class="btn btn-outline-secondary" href="<?= url('finance/transactions', $qs + ['export' => 'csv']) ?>"><i class="bi bi-download"></i> CSV</a></div>
<form class="row g-2 mb-3" method="get"><input type="hidden" name="r" value="finance/transactions">
<div class="col-md-2"><input type="date" class="form-control" name="from" value="<?= e($from) ?>"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="<?= e($to) ?>"></div>
<div class="col-md-2"><select class="form-select" name="type"><option value="">All types</option><?php foreach ($types as $t): ?><option <?= input('type') === $t ? 'selected' : '' ?>><?= e($t) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><select class="form-select" name="direction"><option value="">In & out</option><option value="in" <?= input('direction') === 'in' ? 'selected' : '' ?>>In</option><option value="out" <?= input('direction') === 'out' ? 'selected' : '' ?>>Out</option></select></div>
<div class="col-md-2"><select class="form-select" name="branch"><option value="">All branches</option><?php foreach ($branches as $b): ?><option value="<?= (int)$b['id'] ?>" <?= input('branch') == $b['id'] ? 'selected' : '' ?>><?= e($b['name']) ?></option><?php endforeach; ?></select></div><div class="col-auto"><button class="btn btn-outline-secondary">Filter</button></div></form>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card"><div class="card-body"><div class="small text-muted">Money in</div><div class="stat-value text-success"><?= e(money($sum['i'])) ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><div class="small text-muted">Money out</div><div class="stat-value text-danger"><?= e(money($sum['o'])) ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><div class="small text-muted">Net</div><div class="stat-value"><?= e(money($sum['i'] - $sum['o'])) ?></div></div></div></div></div>
<div class="card"><div class="table-responsive"><table class="table table-sm mb-0 small"><thead class="table-light"><tr><th>Date</th><th>Type</th><th>Method</th><th class="text-end">Amount</th><th>Branch</th><th>Note</th><th>User</th></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><td><?= e($r['txn_date']) ?></td><td><?= e($r['type']) ?></td><td><?= e($r['method']) ?></td><td class="text-end <?= $r['direction'] === 'in' ? 'text-success' : 'text-danger' ?>"><?= $r['direction'] === 'in' ? '+' : '-' ?><?= number_format($r['amount'], 2) ?></td><td><?= e($r['branch_name']) ?></td><td><?= e($r['note']) ?></td><td><?= e($r['username']) ?></td></tr><?php endforeach; ?>
<?php if (!$rows): ?><tr><td colspan="7" class="text-center text-muted py-3">No transactions.</td></tr><?php endif; ?></tbody></table></div></div>
